version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - git fetch --unshallow || true
    - pip install poetry pdoc
    - poetry config virtualenvs.create false
    - poetry self add poetry-dynamic-versioning[plugin]
    - poetry install --all-extras
    - poe docs
    - mkdir -p _readthedocs/html
    - cp --recursive docs/* _readthedocs/html/
