# the following top-level key is required
CONFIG_NINJA_OBJECTS:
  # each second-level key identifies a config-ninja object
  example-1:
    # set the location that the object is written to
    dest:
      output: raw
      path: /etc/datadog-agent/datadog.yaml

    # specify where the object is stored / retrieved from
    source:
      backend: appconfig

      # alternatively, identifiers can be passed directly to '__init__()'
      # init:
      #   kwargs: ...

      # the backend class is instantiated from named resources with its 'new()' method
      new:
        kwargs:
          application_name: Hello World 1
          configuration_profile_name: /dev/etc/datadog-agent/datadog.yaml
          environment_name: dev
