# the following top-level key is required
CONFIG_NINJA_OBJECTS:
  # each second-level key identifies a config-ninja object
  example-local:
    # set the location that the object is written to
    dest:
      output: raw
      path: /tmp/config-ninja-settings.yaml

    # specify where the object is stored / retrieved from
    source:
      backend: local

      init:
        kwargs:
          path: config-ninja-settings.yaml

  example-appconfig:
    dest:
      output: raw
      path: /etc/datadog-agent/datadog.yaml

    source:
      backend: appconfig

      # instantiate the backend class using its 'new()' method
      new:
        kwargs:
          application_name: Hello World 1
          configuration_profile_name: /dev/etc/datadog-agent/datadog.yaml
          environment_name: dev
