# Run this workflow to test Python code changes.
name: 🎨 poe (PR)

on:
  pull_request:
    paths:
      - "**/*.py"
      - "*.py"
      - .pre-commit-config.yaml
      - poetry.lock
      - pyproject.toml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poe
        with:
          poe-task: lint
          poetry-groups: main,dev,lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poe
        with:
          poe-task: test
          poetry-groups: main,dev,test

      - if: always()
        name: Upload coverage reports to codecov.io
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
