# Run this workflow to test Python code changes.
name: 🎨 poe

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poe
        with:
          poe-task: lint
          poetry-groups: main,dev,lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poe
        with:
          poe-task: test
          poetry-groups: main,dev,test

  docs:
    needs:
      - lint
      - test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: lint-docs

      - uses: actions/download-artifact@v4
        with:
          name: test-docs

      - run: |
          mkdir -p ./docs/reports
          mv ./reports ./docs/reports

      - uses: ./.github/actions/poe
        with:
          artifacts: ""
          poe-task: docs

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
